name: Upgrade NPM packages

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  upgrade packages:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Adjust the Node.js version if needed

    - name: Run NPM update
      run: npm update

    - name: Commit and create PR
      uses: peter-evans/create-pull-request@v3
      with:
        title: 'build(deps): Upgrade NPM packages (automated)'
        branch: 'build-deps-upgrade-npm-packages-automated'
        commit-message: 'build(deps): upgrade NPM packages (automated)'
