name: Upgrade NPM packages

on:
  workflow_dispatch:

  schedule:
    - cron:  "0 0 * * 0"

jobs:
  upgrade-packages:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Run NPM update
      run: npm update

    - name: Commit and create PR
      uses: peter-evans/create-pull-request@v7
      with:
        title: 'build(deps): Upgrade NPM packages (automated)'
        branch: 'build-deps-upgrade-npm-packages-automated'
        commit-message: 'build(deps): upgrade NPM packages (automated)'
